name: Initialize
description: 'Composite actions to setup Node environments, and pnpm with cache handling'

inputs:
  deploys_user:
    description: Deploys.app service account
    required: true
  deploys_pass:
    description: Deploys.app secrets
    required: true
  target_image:
    description: Target image name
    required: true

runs:
  using: 'composite'
  steps:
    - uses: docker/setup-buildx-action@v2

    - uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ inputs.target_image }}

    - uses: deploys-app/deploys-action@v1
      with:
        project: rayriffy
        location: gke.cluster-rcf2
        name: ${{ github.event.repository.name }}
        image: ${{ inputs.target_image }}
        minReplicas: 1
        maxReplicas: 4
      env:
        DEPLOYS_AUTH_USER: ${{ inputs.deploys_user }}
        DEPLOYS_AUTH_PASS: ${{ inputs.deploys_pass }}
