name: deploys

on:
  push:
    branches:
      - main

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      HIFUMIN_API_URL: ${{ secrets.HIFUMIN_API_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.actions/initialize
        with:
          hash: ${{ secrets.CACHE_HASH }}
          run_install: 'true'
      - uses: actions/cache@v3
        with:
          path: data
          key: hentai-cache-v2-${{ secrets.CACHE_HASH }}-${{ hashFiles('src/core/constants/codes/**/*.ts') }}
          restore-keys: |
            hentai-cache-v2-${{ secrets.CACHE_HASH }}-${{ hashFiles('src/core/constants/codes/**/*.ts') }}
            hentai-cache-v2-${{ secrets.CACHE_HASH }}-
      - run: pnpm fetch:data
      - run: pnpm sync:data

  build:
    runs-on: ubuntu-latest
    needs: [fetch]
    env:
      APP_NAME: riffyh-runtime-private
      IMAGE_NAME: ghcr.io/rayriffy/riffyh-runtime-private
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: data
          key: hentai-cache-v2-${{ secrets.CACHE_HASH }}-${{ hashFiles('src/core/constants/codes/**/*.ts') }}
          restore-keys: |
            hentai-cache-v2-${{ secrets.CACHE_HASH }}-${{ hashFiles('src/core/constants/codes/**/*.ts') }}
            hentai-cache-v2-${{ secrets.CACHE_HASH }}-

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rayriffy
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.actions/build-and-push
        with:
          target_image: ghcr.io/rayriffy/riffyh-runtime
          deploys_user: ${{ secrets.DEPLOYS_AUTH_USER }}
          deploys_pass: ${{ secrets.DEPLOYS_AUTH_PASS }}
