name: deploys

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: riffyh-runtime
      IMAGE_NAME: ghcr.io/rayriffy/riffyh-runtime
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rayriffy
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        env:
          HIFUMIN_API_URL: ${{ secrets.HIFUMIN_API_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: docker build --build-arg HIFUMIN_API_URL --build-arg DATABASE_URL -t $APP_NAME .

      - name: Tag Docker image
        run: docker tag $APP_NAME $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: deploys-app/deploys-action@v1
        with:
          project: rayriffy-h
          location: gke.cluster-rcf2
          name: riffyh-runtime
          image: ghcr.io/rayriffy/riffyh-runtime
          minReplicas: 1
          maxReplicas: 10
        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
